sudo: required

language: python
python:
  - "3.6"  # used below as $TRAVIS_PYTHON_VERSION in conda install command

before_install:
  - export PACKAGE_NAME=hpc_utils

  # Get and install anaconda (https://conda.io/docs/travis.html)
  - wget -nv https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a  # Useful for debugging any issues with conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no

install:
  # Setting up channels and install dependencies
  - conda config --add channels defaults --add channels vladsaveliev --add channels bioconda --add channels conda-forge
  - conda install -q python=$TRAVIS_PYTHON_VERSION pip requests conda-build jinja2 anaconda-client ngs_utils
  # Building package
  - conda build deploy/conda_package/${PACKAGE_NAME}
  - conda install --use-local ${PACKAGE_NAME}

script:
  - python -c "from hpc_utils.hpc import find_loc; print(find_loc())"

deploy:
  # Deploy to Anaconda.org
  - provider: script
    script: ./deploy/deploy_anaconda.sh $PACKAGE_NAME $ANACONDA_TOKEN
    on:
      tags: true
    skip_cleanup: true

